name: Cross Platform Test

on: workflow_dispatch

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Show OS
        run: echo "Running on ${{ matrix.os }}"
