name: multiple jobs
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: echo "testing"
      - name: checkout the git
        uses: actions/checkout@v7
      - name: list the dir
        run: ls
  second-job:
    
    runs-on: ubuntu-latest
    steps:
      - name: second job running
        run: echo "second job running"
      - name: checkout the job
        uses: actions/checkout@v7
      - name: list the dir
        run: ls
