
name: GIT job testing
on: 
  pull_request:
    branches:
      - main
      - test
      - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "welcome"
      - name: checkout the code
        uses: actions/checkout@v7
      - name: listing the files
        run: ls
  testing:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: running second job
        run: echo "second job running"
        
